# Generated by Django 5.2.8 on 2026-02-24 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзыв'},
        ),
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
    ]
