# Generated by Django 5.2.8 on 2026-02-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URl')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='card_images', verbose_name='Изображение')),
                ('tages', models.TextField(blank=True, null=True, verbose_name='теги')),
            ],
            options={
                'verbose_name': 'Карточки',
                'verbose_name_plural': 'Карта',
                'db_table': 'card',
            },
        ),
    ]
