# Generated by Django 5.2.8 on 2026-03-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='image',
            new_name='imageScnd',
        ),
        migrations.AddField(
            model_name='cards',
            name='age',
            field=models.TextField(blank=True, null=True, verbose_name='Продолжительность жизни'),
        ),
        migrations.AddField(
            model_name='cards',
            name='furr',
            field=models.TextField(blank=True, null=True, verbose_name='Тип шерсти'),
        ),
        migrations.AddField(
            model_name='cards',
            name='furrColors',
            field=models.TextField(blank=True, null=True, verbose_name='Окрасы'),
        ),
        migrations.AddField(
            model_name='cards',
            name='height',
            field=models.TextField(blank=True, null=True, verbose_name='Рост'),
        ),
        migrations.AddField(
            model_name='cards',
            name='imageMain',
            field=models.ImageField(blank=True, null=True, upload_to='card_images', verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='cards',
            name='imageThrd',
            field=models.ImageField(blank=True, null=True, upload_to='card_images', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='cards',
            name='weight',
            field=models.TextField(blank=True, null=True, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='tages',
            field=models.TextField(blank=True, null=True, verbose_name='Теги'),
        ),
    ]
