# Generated by Django 5.2.8 on 2026-03-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_image_cards_imagescnd_cards_age_cards_furr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='tages',
        ),
    ]
