# Generated by Django 5.2.8 on 2026-03-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_cards_tages'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='tages',
            field=models.TextField(blank=True, null=True, verbose_name='Теги'),
        ),
    ]
