# Generated by Django 5.2.8 on 2026-03-31 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_cards_tages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория тегов',
                'verbose_name_plural': 'Категории тегов',
            },
        ),
        migrations.RemoveField(
            model_name='cards',
            name='tages',
        ),
        migrations.AddField(
            model_name='cards',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cards', to='catalog.tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='catalog.tagcategory', verbose_name='Категория'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('category', 'name')},
        ),
    ]
