# Generated by Django 6.0.2 on 2026-05-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_tag_tagcategory_remove_cards_tages_cards_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='furr',
        ),
    ]
