# Generated by Django 6.0.2 on 2026-05-05 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_cards_furr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_users', to='catalog.cards', verbose_name='Карточка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_cards', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранная карточка',
                'verbose_name_plural': 'Избранные карточки',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'card'), name='unique_user_favorite_card')],
            },
        ),
    ]
