# Generated by Django 6.0.2 on 2026-05-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_favoritecard'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='health',
            field=models.TextField(blank=True, null=True, verbose_name='Здоровье'),
        ),
    ]
