# Generated by Django 6.0.2 on 2026-05-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_cards_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='health',
            field=models.TextField(blank=True, null=True, verbose_name='Результат'),
        ),
    ]
