# Generated by Django 6.0.2 on 2026-05-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_cards_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='qresult',
            field=models.TextField(blank=True, null=True, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='health',
            field=models.TextField(blank=True, null=True, verbose_name='Здоровье'),
        ),
    ]
