# Generated by Django 6.0.2 on 2026-05-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_cards_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='URl'),
        ),
    ]
