# Generated by Django 6.0.2 on 2026-05-03 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_cards_furr'),
        ('qtest', '0002_testresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название шага')),
                ('order', models.PositiveIntegerField(unique=True, verbose_name='Порядок')),
                ('weight', models.PositiveIntegerField(default=1, verbose_name='Вес шага')),
            ],
            options={
                'verbose_name': 'Шаг теста',
                'verbose_name_plural': 'Шаги теста',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['question__step', 'question__order', 'order'], 'verbose_name': 'Ответ теста', 'verbose_name_plural': 'Ответы теста'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['step', 'order'], 'verbose_name': 'Вопрос теста', 'verbose_name_plural': 'Вопросы теста'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'Результат теста', 'verbose_name_plural': 'Результаты теста'},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='tags',
        ),
        migrations.AddField(
            model_name='answer',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='answer',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='catalog.tag', verbose_name='Тег ответа'),
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок внутри шага'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='total_score',
            field=models.PositiveIntegerField(default=0, verbose_name='Итоговые баллы'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qtest.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='step',
            field=models.PositiveIntegerField(verbose_name='Номер шага'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='best_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_results', to='catalog.cards', verbose_name='Лучший результат'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='cards',
            field=models.ManyToManyField(blank=True, to='catalog.cards', verbose_name='Карточки результата'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='tags',
            field=models.ManyToManyField(blank=True, to='catalog.tag', verbose_name='Полученные теги'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
