# Generated by Django 6.0.2 on 2026-05-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
